apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: "c3FsMDEK"
  MYSQL_USER: "dXNlcjEK"
  MYSQL_PASSWORD: "cGFzc3dvcmQK"
  MYSQL_ROOT_PASSWORD: "cGFzc3dvcmQxMjMK"