apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
  labels:
    app: print-envars-greeting

spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: bash-container
      image: bash
      command: ["bash"]
      args: ["-c","echo $(GREETING) $(COMPANY) $(GROUP)"]
      env:
      - name: GREETING
        value: "Welcome To"
      - name: COMPANY
        value: "DevOps"
      - name: GROUP
        value: "Industries"

      # - name: SPECIAL_LEVEL_KEY
      #   valueFrom:
      #     configMapKeyRef:
      #       # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
      #       name: special-config
      #       # Specify the key associated with the value
      #       key: special