apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    app: static-busybox

spec:
  containers:
    - name: static-busybox-container
      image: busybox:1.28.4
      command: [ "sleep", "1000" ]