apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  volumes:
    - name: nginx-log-storage
      persistentVolumeClaim:
        claimName: claim-log-1
  containers:
    - name: webapp-container
      image: nginx
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: nginx-log-storage