apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-job
spec:
  template:
    spec:
      containers:
      - name: container-countdown-job
        image: debian:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "for i in ten nine eight seven six five four three two one ; do echo $i ; done;" ]
      restartPolicy: Never
  backoffLimit: 4