apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-replicaset

spec:
  template:
    metadata:
      name: myapp-busybox-pod
      labels:
        app: myapp-busybox

    spec:
      containers:
        - name: busybox-container
          image: busybox
  replicas: 5
  selector:
    matchLabels:
      app: myapp-busybox