#!/bin/bash 
shopt -s extglob 
echo "Please enter first name" 
read fsName 
until [[ "$fsName" == +([[:alpha:]]) ]]; do
    echo "Please enter string" 
    read fsName
done 

echo "Please enter last name" 
read lsName 
until [[ "$lsName" == +([[:alpha:]]) ]]; do
    echo "Please enter string" 
    read lsName
done 

echo "Please enter dept. name"
read deptName
until [[ "$deptName" == +([[:alpha:]]) ]]; do
    echo "Please enter string" 
    read deptName
done 

echo "Please enter phone"
read phone 

dbPhone=$(awk -F "," '$3=='$phone' {print $3}' DB)

while [[ true ]]; do
    
    if [[ "$phone" == +([[:digit:]]) ]]
    then
        if [ -z $dbPhone ]
        then
            break
        fi
    fi

    echo "This phone is repeated or not valid,please enter another one" 
    read phone

    dbPhone=$(awk -F "," '$3=='$phone' {print $3}' DB)
done 


echo "Please enter salary" 
read salary 
until [[ "$salary" == +([[:digit:]]) ]]; do
    echo "Please enter number" 
    read salary
done 

echo "$fsName,$lsName,$phone,$deptName,$salary" >> DB

echo "inserted successfully !"
